//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication_CDPMI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class news
    {
        public int newsID { get; set; }
        public string newsTitle { get; set; }
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}")]
        public System.DateTime publishTime { get; set; }
        public int readCount { get; set; }
        public string contentText { get; set; }
    }
}
