//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication_CDPMI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productCategory
    {
        public productCategory()
        {
            this.product = new HashSet<product>();
        }
    
        public int categoryID { get; set; }
        public string categoryName { get; set; }
        public string memo { get; set; }
    
        public virtual ICollection<product> product { get; set; }
    }
}
