//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication_CDPMI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebEntities : DbContext
    {
        public WebEntities()
            : base("name=WebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin> admin { get; set; }
        public DbSet<basicSetting> basicSetting { get; set; }
        public DbSet<feedback> feedback { get; set; }
        public DbSet<flash> flash { get; set; }
        public DbSet<friendLink> friendLink { get; set; }
        public DbSet<logRecord> logRecord { get; set; }
        public DbSet<news> news { get; set; }
        public DbSet<product> product { get; set; }
        public DbSet<productCategory> productCategory { get; set; }
        public DbSet<service> service { get; set; }
    }
}
