//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication_PMIEnglishSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback_en
    {
        public int id { get; set; }
        public string title { get; set; }
        public System.DateTime createTime { get; set; }
        public string mainContent { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string cname { get; set; }
    }
}
