//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication_PMIEnglishSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class friendLink_en
    {
        public int id { get; set; }
        public string friendLinkTitle { get; set; }
        public string friendLink { get; set; }
    }
}
