//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication_PMIEnglishSite.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pmienglish : DbContext
    {
        public pmienglish()
            : base("name=pmienglish")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<admin_en> admin_en { get; set; }
        public DbSet<basicSetting_en> basicSetting_en { get; set; }
        public DbSet<feedback_en> feedback_en { get; set; }
        public DbSet<flash_en> flash_en { get; set; }
        public DbSet<friendLink_en> friendLink_en { get; set; }
        public DbSet<logRecord_en> logRecord_en { get; set; }
        public DbSet<news_en> news_en { get; set; }
        public DbSet<product_en> product_en { get; set; }
        public DbSet<productCategory_en> productCategory_en { get; set; }
        public DbSet<service_en> service_en { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
        public DbSet<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
    }
}
